name: Run tests
on: [push, pull_requests]
job:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # get Repo
      - uses: actions/checkout@v2
      # setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
      # lint with flake8
      - name: Linter validation
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pytest
        run: pytest -s -vv
